name: Pre-Commit E2E Tests in Android

# For now leaving as PR so that we can test the functionality without pushing to master branch
on: [pull_request]

jobs:
  e2e_test:
    name: E2E PCloudy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: "rationally-app/mobile-e2e"
          token: ${{ secrets.TESTING }}
      - run: ls
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Setup Appium
        run: npm install appium -g
      - name: Setup E2E Environment
        run: |
          wget -O Exponent.apk http://expo.io/--/api/v2/versions/download-android-apk
          pip3 install -r requirements.txt
      - name: Run E2E Tests
        run: ./stg_loginflow_deeplink_pCloudy.sh
      - name: Upload Appium Logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: output_android
          path: |
            ./log.html
            ./report.html
            ./output.xml
            ./appium_kill_stdout.txt
            ./appium-screenshot-1.png
